server:
  port: 8081

spring:
  dataSource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled=true:

